# Quy tắc 1 (Ưu tiên): BẢO VỆ BẰNG MẬT KHẨU
[[redirects]]
  from = "/*"
  to = "/*"
  status = 401
  force = true
  headers = {Authorization = ["Basic " + ENV.BASIC_AUTH_SECRET]}

# Quy tắc 2: FIX LỖI 404 SAU KHI ĐĂNG NHẬP
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
