# === Cấu hình Cho phép truy cập và fix lỗi 404 (SPA Routing) ===
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# === Cấu hình Bảo vệ bằng Mật khẩu (Basic Auth) - Sử dụng Biến môi trường ===
[[redirects]]
  from = "/*"
  to = "/*"
  status = 401
  force = true
  headers = {Authorization = ["Basic " + ENV.BASIC_AUTH_SECRET]}
